// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0ULUS8jVhHCKRv55xupk8aGe1TWjfAE',
    appId: '1:801051530454:web:ea38b970cb4b9ef177e577',
    messagingSenderId: '801051530454',
    projectId: 'memz-ae633',
    authDomain: 'memz-ae633.firebaseapp.com',
    storageBucket: 'memz-ae633.appspot.com',
    measurementId: 'G-2LJY3DWS8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO1wPh96HWY-AHIgIt97vbUTcQHYFCHGU',
    appId: '1:801051530454:android:9e3e3b7c9b0af7a377e577',
    messagingSenderId: '801051530454',
    projectId: 'memz-ae633',
    storageBucket: 'memz-ae633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBMy45SJ5YLmsBMaI6ReLJYsaSfvlywU',
    appId: '1:801051530454:ios:2091a95c8c36848477e577',
    messagingSenderId: '801051530454',
    projectId: 'memz-ae633',
    storageBucket: 'memz-ae633.appspot.com',
    iosClientId: '801051530454-g8ankemrhg0uul9brrls0e2o926ic310.apps.googleusercontent.com',
    iosBundleId: 'com.example.memz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEBMy45SJ5YLmsBMaI6ReLJYsaSfvlywU',
    appId: '1:801051530454:ios:2091a95c8c36848477e577',
    messagingSenderId: '801051530454',
    projectId: 'memz-ae633',
    storageBucket: 'memz-ae633.appspot.com',
    iosClientId: '801051530454-g8ankemrhg0uul9brrls0e2o926ic310.apps.googleusercontent.com',
    iosBundleId: 'com.example.memz',
  );
}
