// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAUMPCsiB0wXLVH9xnN1tFvrQykeqdZqs',
    appId: '1:717737182106:web:3958259d9e3515e4c3f023',
    messagingSenderId: '717737182106',
    projectId: 'memz-prod',
    authDomain: 'memz-prod.firebaseapp.com',
    storageBucket: 'memz-prod.appspot.com',
    measurementId: 'G-BSD7ZVPJQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0ilMfLpXq5Yvdf6WWo8-FuXTuQoh5Js',
    appId: '1:717737182106:android:6bfbfbbbb478e406c3f023',
    messagingSenderId: '717737182106',
    projectId: 'memz-prod',
    storageBucket: 'memz-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZ4thW8Ppayh5rFI14fxWVeuPQ3gcud4',
    appId: '1:717737182106:ios:661856aff322881ec3f023',
    messagingSenderId: '717737182106',
    projectId: 'memz-prod',
    storageBucket: 'memz-prod.appspot.com',
    iosClientId: '717737182106-i3sircjkokeg6c28bk57jgu688f3eh7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.memz',
  );
}
